# --8<-- [start:workspace]
[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[dependencies]
smcnn-core = { path = "packages/smcnn/core" }
genbrain = { path = "." }
python = "<=3.12"
# --8<-- [end:workspace]


[tasks]
start = "rich-example-main"

[package]
name = "genbrain"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies]
hatchling = "==1.26.3"
python = "<=3.12"

[package.run-dependencies]

[pypi-dependencies]
genjax = ">=0.9.2, <0.10"
