[project]
authors = [{name = "Aaron Steele", email = "aaron@chi-fro.org"},{name = "Andrew Bolton", email = "andrew@chi-fro.org"}]
description = "Point Light Studio is a Python library for visualizing point light illusions."
name = "pls"
requires-python = ">= 3.11"
version = "0.1.0"
dependencies = ["jax==0.4.35", "pillow>=10.4.0,<11", "ipython", "ipykernel", "genjax>=0.8.2.dev1,<0.9", "genstudio>=2025.2.2,<2026"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
pls = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
cmake = ">=3.31.5,<4"
numpy = "<2.0.0"
ipykernel = ">=6.29.5,<7"
