---
format:
  html:
    theme: cyborg
---

# Transgenics that are clean and informative: 
* Layer II / III:
    - SepW1
* Layer IV: 
    - Nr5a1
* Layer V:
    - Tlx3: Targets CP, Cortex
    - A930038C07Rik-Tg1-Cre, Sim1-Cre: Targets CP, Thalamus, SC
    - Efr3a-Cre: Recurrent Layer 5 (Off target Layer 6 expression accounts for visual thalamus proj. according to [Kim et al.](https://pubmed.ncbi.nlm.nih.gov/26671462/)
    - Rbp4: Labels both Tlx and Sim layer 5 neurons. 

# Anatomical Predictions of SMCNNs

* Layer 2/3 -> 4 connections mediate data driven (botom up proposal) and top down (model-based) CPTs. 
* BG neurons are aggregate particle scores. Multiple brain regions should converge on one BG neuron. Connected BG neurons should have the same input pattern. 
* The pathway through the C-BG-T-C loop has to be closed and return to the exact source columns. Multi-synaptic retrograde tracing through the C-BG-T-C loop would work here:
    - We know the C -> BG projection is one directional. 
    - We know the BG -> T projection is one directional (in LP, not LD)
    - We know the T -> C loop using Tlx3 is one directional (i.e. Tlx3 neurons do not go to the thalamus). Also SepW1 and Nr5a1 do not go to thalamus. 
    Therefore, if we inject into neural subsets in cortex that do NOT go to thalamus (i.e. L2/3 SepW1, Nr5a1, Tlx3), we will get second order thalamic inputs. If those travel two synapses, 
    they will go to BG; if those end up back at the cortical source site, can we get a readout of it? 

# Questions 
* Is there a way of identifying founder cells vs. input cells in a local microcircuit? 

# Activity + Anatomy Ideas:
* SC projecting neurons should be state specific and topographic 



