---
format:
  html:
    theme: cyborg
--- 

__Neuroscientists' quest to understand consciousness is a hot topic right now, yet you often pose things via psychology, which seems to be taken less seriously. Are you behind the curve?__

_"I don't see neuroscience as serious. What they have are nutty little theories, and they do elaborate experiments to confirm them and don't know what to do if they don't work....When you talk to neuroscientists, they seem so unsophisticated; they major in biology and know about potassium and calcium channels, but they don't have sophisticated psychological ideas. Neuroscientists should be asking: What phenomenon should I try to explain? Can I make a theory of it? Then, can I design an experiment to see if one of those theories is better than the others? If you don't have two theories, then you can't do an experiment. And they usually don't even have one."_  - Marvin Minsky 

# Theory Hour Planning: 

## General Idea: 
    We have a cool 2D->3D model that we will iterate on as a group (i.e. like the Hackathon)
* Why Simple 2D->3D Vision? 
    + Vision is the best characterized system in the brain (but still not so much)
    + There is a clear alternative hypothesis to our approach (Deep Neural Networks) 
    + Visual illusions are salient and interesting / work across species / aid in characterizing computations 
    + There is a long history of Point Light work in Gestalt Psychology that has not been approached programatically 
    + There are severe deficits of fragmentation / meaning misinterpretation in mental illness 

* Why SMC? What does SMC predict about brains / cognition that other theories do not? 
    + Particle Filters and Cognition
        - Vul 2009, 2014
        - Xuan: SIPS, GenParticleFilters   
    + Uncertainty Representation in Brains 
        - How is uncertainty represented in SMCNNs?        
        - Marginal Likelihood and its complete lack of investigation in any neuroscience experiment (how it happens in SMCNNs)
        - How do Alternative Neural Mechanisms fit or not? (WeiJi Ma, Wolfgang Maas, Sam Gershman)
    + Comparison of incoming data to expectation in Neuroscience 
        - Predictive Coding (Keller, Mrsic, Carandini)
        - Free Energy Principle (Friston)
        - Efference Copy 
    + Examination of Bayesian Alternatives (i.e. Gibbs sampling, Neural Networks, Variational Inference) 

* Applications of Information Theory to Inference Patterns: 

| Principle | Vision Model | Morse Code Model |
|---------|:-----|------:|
| Noisy Channel (Corruption) | Light refracted by rain, fog | - to . via user input / mechanical error |
| Noisy Channel (Missing Data) |  Occlusion, Blinking | Sending failure. Unplug event. |
| Code Redundancy | The same 2D sensor pattern maps to multiple _Percepts_ | The same code maps to multiple _Words_ | 
| Missing Code | The World does not contain the _Percept_ (i.e. its Features, Motion Model) | The Language does not contain the _Word_ | 
| Level Crossings (2) | Objects inform Shape inform Edge / Surfaces inform Light| Words inform phonics inform letters inform code | 
| Data Structures (3) | Structure of generative visual knowledge (motion scene graphs, 3D voxel grids, 2D feature maps, Surfaces) | Structure of generative language (grammars, sentences, conversations) | 

* Our 2D->3D Model 
    + Capabilities To Add (Coding in Theory Hour) 
        - Velocity Model (non-smooth: GP, basis functions, wavelets)
        - Grammar of Thought Dynamics Models (Tracey Mills)        
        - Viewpoint / Pose of observer 
        - Addition of reference cube 
        - Multiple Dots
    + Latent variable representations
        - Pattern Theory
        - Grid Cells / Place Cells
        - Static Transforms (ego->allo, allo->ego)
    + Exension to other domains
        - Dots gain goals and intent based on learned features (e.g. Heider and Simmel)
        - Dots with particular features are worth more (i.e. identification of the feature is extra rewarding, but rare)
        - Motion Scene Graphs (data structures of the visual system)
        - Noisy / degraded dot patterns (e.g. clojure lib) / blinking / occluders 
    + References
        - "Perceiving Events and Objects"
        - "Perception as Bayesian Inference"

* SMCNN Architecture
    + Functionality 
    + Mapping to Neural Architecture
        - Cortical Microcolumns in Neuroscience History 
        - Intracortical Connections in the Visual System (with techniques from Ian)
        - Activity Patterns in the Cortical Visual System (with Caroline) 
        - Cortico-BG-Thalamic-Cortical Loops 
        - The Midbrain Visual System and likelihood
    + Classes of Predictions
        - EEGs 
        - Poisson Spiking
        - Phase Precession
        - Gaussian Receptive Fields
        - Some neurons symbolic, some not 
        - Repeated / general purpose modules of microcolumns 
        - Stereotyped Microcolumnar Connectivity 
        - Loop architecture
    + Speed Issues, Clunkiness of Interface Issues
        - Solution with GenSP
        - Use GenSP with more realistic neural simulators 
    
# TOPIC CHECKLIST:
## Where are we now in the GenBrain Tech Stack? 
- [ ] Go through the 2D->3D model only (no proposal yet)
- [ ] Show the primitive distribution types used in SMCNNs. Implement simulate and get_score. 
- [ ] Show how you can get the arguments to each categorical within the trace. 
- [ ] Show math for how probabilities can be turned into poisson processes. Show SMCNN sampling from the prior and scoring from P. Show variance of estimate. Implement in GenSP / Equate with binomial. Try to implement P-scoring in GenSP the way the interpreter does it, and extract spikes. 
- [ ] Show particle filtering side-by-side with SMCNNs. Introduce proposal distributions as a way of getting latents. 
- [ ] Show that probability estimates don't hold with division. Show the way SMCNN handles this and the problems that arise. 
- [ ] Introduce RAVI stacks. 
- [ ] Resampling / Rejuvenation / Particle Gibbs. Implementation in SMCNNs.

## What aspects of a good 2D->3D model are we missing? 
- [ ] Multiple objects 
- [ ] Motion models than can symbolically capture velocity patterns
    * GPs
    * Symbolic Diff Eq Parameters
    * Wavelets
    * Basis Functions     
- [ ] Scene Graphs / Data structures / variable-res 3D voxel representations (allo / ego)

## What _Inference Concepts_ are we missing? 
- [ ] Learning the 3D motion statistics of a dot type 
- [ ] Learning the utility of a type 
- [ ] Inference Control
- [ ] Trace storage i.e. Kevin's example. Keeping whole traces around and explaining them. 
- [ ] Summary statistics / conjugacy. Passing parameters rather than state. (I.e. i can describe the distributions of known variables without scoring)

## What aspects of Neuroscience Can We Address? 
- [ ] Data structures implemented in neurons (COMPLETELY unexplored and most interesting). Grid codes, place codes. What is the form of more complex latents? 
- [ ] Implement GenSP on top of Jax-compatible biosimulators. 
- [ ] Assign computational roles to neuromodulator systems known to be involved in learning and utility. 
- [ ] Assign model structure to particular brain regions and test
- [ ] Generate filtered activity (waves) and compare to EEG signals from regions we hypothesize are mediating the model.  

## What aspects of Psychology can we explain? 
- [ ] Gestalt perception as split-merge inference in a symbolic scene graph. 
- [ ] 3D hints (perspective cues, slight size change, occluders, self motion)