---
format:
 # pdf:
 #   documentclass: scrartcl
 #   papersize: letter
  html:
    theme: cyborg
--- 

# Phenomenon to explain / Compelling Stimuli

Weiss and Adelson 
Nakayama and Shimoju

# Neurobiological Influences

V1 is depth sensitive:

[In binocular V1 of mice, neurons show disparity sensitivity](https://journals.physiology.org/doi/epdf/10.1152/jn.01021.2012)

[This is a repeat of a long known result in primates, where almost every V1 neuron in the binocular zone is depth sensitive](https://journals.physiology.org/doi/abs/10.1152/jn.1977.40.6.1392)

[Visual cliff performance is disrupted by binocular or monocular V1 in mice in this paper by Cris Niell's Lab](https://elifesciences.org/articles/74708#content)




SC induces blindness

# Marr's Vision

+ Low level symbolic feature sets combine into higher level percepts

+ Visual structure emerges from the combination of evolutionarily / physically relevant phenomenon (Basically the exact Gestalt Perception Idea). 
    1) Size
    2) Similarity 
    3) Common Fate
    4) 

Marr's work seems to be missing two components that are fundamental to functioning biological visual systems:
  1. Bayes Rule: Marr's work generates a 2D bitmap for each feature (blobs, terminations, edges). It is likely these are actually probabilities in brains. This would also make uncertainty in the position easier to handle (i.e. if you are predicting a bitmap, and you are 1 spatial div off in feature space, will be completely off on the score; just as much as if you were very positionally wrong). 

  2. Actual neurobiology: Marr's work cites a small set of visual neuroscience studies that focus largely on the neocortex. Marr's zero-crossing detectors are certainly present (alpha-RGCs) but the symbolic content of the early visual system is already accomplishing many of the 2D raw primal sketch's computations. Moreover, there is clear structure in the visual system that is lacking in Marr's ideas. 


# Likelihood
## ChiCON Summer 2024 Likelihood Discussion Summary:

## Josh: 

- In the 90s: Simple models of probabilistic vision with no probabilistic programs. Simple pedagogical examples in talks using Bayesian statistics and gaussian likelihoods. Gaussian pixel noise. One dimension of brightness or RGB.
- Extend to gaussian likelihoods in more interesting feature spaces.
- Texture of Texture representation.
- One-Shot Learning with a Hierarchical Nonparametric Bayesian Model
- Structure Driven Image Database Retrieval
- Cloth over objects (Ilker) — using double convnet idea.
- History and hierarchy of squared error feature spaces — we should explore multiple points here. Recent consensus is its pretty good to do this in pretrained convnet feature space. Could do a combo of gaussian pixel noise. Independent discrete pixel noise → Smoothed gaussian pixel noise → feature spaces with more interesting features.
- Comparisons could happen at various levels — could also be in the neocortex, with traditional ideas being that V1 is the likelihood.
- Could also be that there’s a likelihood mismatch happening at various levels of cortex that are  SENDING attentional signals to the tectum.

## Kevin:

- Visual metamers. You look at something and you can’t tell it apart from something else even if there are tons of pixel differences. Rustling grass. You can have videos where there is NO pixel overlap, but still the same answer. General idea is When i’m looking at the same sorts of stuff in the world, I should see it as the same.
- [Cameron brings up the Juelez conjecture](https://www.sciencedirect.com/science/article/pii/0022249681900390)
- Gabors — what is it about gabors that make it impervious to noise, but not to angles. They don’t pick up pixel based noise. They pick up orientation to edges in the image. And temporal gabors (wavelets).

## Andrew:

- Yudi’s task. Minsky — do one thing but be able to do it in many ways. In his case, you do NOT want to average and you want to care deeply about bitflip pixel noise.
- Insanely bad scores for very good guesses — this is the major problem we’re facing. If the letter is a few pixels off but generally good, your likelihood score spikes downwards.

## Mccoy: 

- Wide variety of styles that you could see. Cached representation to put the STYLE on. The decoder takes a latent representation of the image and tries to construct an image from this. You can take the idiom of the autoencoder and put it as a piece into a probabilistic model. Latent features that deal with poses and quantity of objects.
- Kevin — V1 cashes out in edges and hypercomplex cells.
- Get features aligned in 3D space — probabilistic renderer. Wiggle a latent — probabilistic process of ASSEMBLING an image. Place the features around to describe a distribution, and through that distribution a likelihood through the image. Lots of auxiliary randomness in choosing how to wiggle, how to adjust. Need to put inference on the inside of that process! What you really care about is a marginal of that process. You can write down a rendering process in the form Mccoy descirbed; you have to handle normalizing this thing.

Andrew

- Draws out 3D representation of edges on the board — V1 contains 3D primitives, not 2D. The edge is different at different depths, but to the tectum, its the same, with maybe a “depth cue” added as a likelihood value (i.e. a scalar). Many 3D edges can generate the same 2D image — this is key to likelihood. Clearly fish and frogs don’t have great 3D localization without their binocular zones, because they strike at lights 2 centimeters away. More fixed action based on 2D cues.

References: 

[Geman and Geman, 1984](https://www.dam.brown.edu/people/geman/Homepage/Image%20processing,%20image%20analysis,%20Markov%20random%20fields,%20and%20MCMC/stochastic%20relaxation.pdf). 

Josh argues that likelihood could be in V1, but Andrew counters that nearly all foveal V1 neurons are sensitive to [depth in primates](https://journals.physiology.org/doi/abs/10.1152/jn.1977.40.6.1392), meaning 3D features are bottoming out in V1, not 2D. It is also clear that rodents have binocular and monocular representations of depth in V1, when they perform the [visual cliff task](https://www.biorxiv.org/content/biorxiv/early/2021/10/01/2021.09.29.462468.full.pdf), in [multiple studies](www.cell.com/current-biology/pdf/S0960-9822(21)00272-4.pdf). 
